export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'

export const INCREMENT_LOADING_PROGRESS = 'INCREMENT_LOADING_PROGRESS'
export const RESET_LOADING_PROGRESS = 'RESET_LOADING_PROGRESS'

export const GET_TOKEN = "GET_TOKEN"
export const SAVE_TOKEN = "SAVE_TOKEN"
export const GET_TOKEN_AF = "GET_TOKEN_AF"